In [1]:
# getting started with basics of numpy 


In [2]:
import numpy as np

In [3]:
mylist=[1,2,3,4,5]
#  converting list into an array
# single dimensional array 
x=np.array(mylist)
x

array([1, 2, 3, 4, 5])

In [4]:
y=np.array([2,4,5,6,])
y

array([2, 4, 5, 6])

In [5]:
# making a multidimensional array


In [8]:
list1=[1,2,3]
list2=[3,4,5]
m=np.array([list1,list2])
m

array([[1, 2, 3],
       [3, 4, 5]])

In [10]:
#  two know the built in function of the array 
m.shape

(2, 3)

In [13]:
# creating a array by the concept of range so u give start,stop,stepsize 
n=np.arange(0,1000,2)
n

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [14]:
n.shape

(500,)

In [17]:
# changing dimension of an array 
# use the built in function called reshape to change the dimension of the array
n=n.reshape(250,2)

In [18]:
n

array([[  0,   2],
       [  4,   6],
       [  8,  10],
       [ 12,  14],
       [ 16,  18],
       [ 20,  22],
       [ 24,  26],
       [ 28,  30],
       [ 32,  34],
       [ 36,  38],
       [ 40,  42],
       [ 44,  46],
       [ 48,  50],
       [ 52,  54],
       [ 56,  58],
       [ 60,  62],
       [ 64,  66],
       [ 68,  70],
       [ 72,  74],
       [ 76,  78],
       [ 80,  82],
       [ 84,  86],
       [ 88,  90],
       [ 92,  94],
       [ 96,  98],
       [100, 102],
       [104, 106],
       [108, 110],
       [112, 114],
       [116, 118],
       [120, 122],
       [124, 126],
       [128, 130],
       [132, 134],
       [136, 138],
       [140, 142],
       [144, 146],
       [148, 150],
       [152, 154],
       [156, 158],
       [160, 162],
       [164, 166],
       [168, 170],
       [172, 174],
       [176, 178],
       [180, 182],
       [184, 186],
       [188, 190],
       [192, 194],
       [196, 198],
       [200, 202],
       [204, 206],
       [208,

In [19]:
n=n.reshape(125,4)

In [20]:
n

array([[  0,   2,   4,   6],
       [  8,  10,  12,  14],
       [ 16,  18,  20,  22],
       [ 24,  26,  28,  30],
       [ 32,  34,  36,  38],
       [ 40,  42,  44,  46],
       [ 48,  50,  52,  54],
       [ 56,  58,  60,  62],
       [ 64,  66,  68,  70],
       [ 72,  74,  76,  78],
       [ 80,  82,  84,  86],
       [ 88,  90,  92,  94],
       [ 96,  98, 100, 102],
       [104, 106, 108, 110],
       [112, 114, 116, 118],
       [120, 122, 124, 126],
       [128, 130, 132, 134],
       [136, 138, 140, 142],
       [144, 146, 148, 150],
       [152, 154, 156, 158],
       [160, 162, 164, 166],
       [168, 170, 172, 174],
       [176, 178, 180, 182],
       [184, 186, 188, 190],
       [192, 194, 196, 198],
       [200, 202, 204, 206],
       [208, 210, 212, 214],
       [216, 218, 220, 222],
       [224, 226, 228, 230],
       [232, 234, 236, 238],
       [240, 242, 244, 246],
       [248, 250, 252, 254],
       [256, 258, 260, 262],
       [264, 266, 268, 270],
       [272, 2

In [24]:
# linspace is function which is similiar to arange 
o=np.linspace(0,10,100)
# we tell starting ,ending value, numberof intervals and splits up the intreval accordingly
o

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [25]:
o.resize(10,10)

In [33]:
o.resize(50,2)

In [31]:
o

array([[ 0.        ,  0.1010101 ],
       [ 0.2020202 ,  0.3030303 ],
       [ 0.4040404 ,  0.50505051],
       [ 0.60606061,  0.70707071],
       [ 0.80808081,  0.90909091],
       [ 1.01010101,  1.11111111],
       [ 1.21212121,  1.31313131],
       [ 1.41414141,  1.51515152],
       [ 1.61616162,  1.71717172],
       [ 1.81818182,  1.91919192],
       [ 2.02020202,  2.12121212],
       [ 2.22222222,  2.32323232],
       [ 2.42424242,  2.52525253],
       [ 2.62626263,  2.72727273],
       [ 2.82828283,  2.92929293],
       [ 3.03030303,  3.13131313],
       [ 3.23232323,  3.33333333],
       [ 3.43434343,  3.53535354],
       [ 3.63636364,  3.73737374],
       [ 3.83838384,  3.93939394],
       [ 4.04040404,  4.14141414],
       [ 4.24242424,  4.34343434],
       [ 4.44444444,  4.54545455],
       [ 4.64646465,  4.74747475],
       [ 4.84848485,  4.94949495],
       [ 5.05050505,  5.15151515],
       [ 5.25252525,  5.35353535],
       [ 5.45454545,  5.55555556],
       [ 5.65656566,

In [ ]:
# One major difference is reshape() does not change your data but resize() does change it. resize() first accommodates all the values in original array, after that if extra space is there (or size of new array is greater than original array), then it adds its own values

In [34]:
# several built in one functions and shortcuts in building arrays 

In [36]:
np.ones(10,10) # returns the arrays of ones

TypeError: data type not understood

In [37]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
# return array of zeros 
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])