In [1]:
# getting started with basics of numpy 


In [2]:
import numpy as np

In [3]:
mylist=[1,2,3,4,5]
#  converting list into an array
# single dimensional array 
x=np.array(mylist)
x

array([1, 2, 3, 4, 5])

In [4]:
y=np.array([2,4,5,6,])
y

array([2, 4, 5, 6])

In [5]:
# making a multidimensional array


In [8]:
list1=[1,2,3]
list2=[3,4,5]
m=np.array([list1,list2])
m

array([[1, 2, 3],
       [3, 4, 5]])

In [10]:
#  two know the built in function of the array 
m.shape

(2, 3)

In [13]:
# creating a array by the concept of range so u give start,stop,stepsize 
n=np.arange(0,1000,2)
n

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [14]:
n.shape

(500,)

In [17]:
# changing dimension of an array 
# use the built in function called reshape to change the dimension of the array
n=n.reshape(250,2)

In [18]:
n

array([[  0,   2],
       [  4,   6],
       [  8,  10],
       [ 12,  14],
       [ 16,  18],
       [ 20,  22],
       [ 24,  26],
       [ 28,  30],
       [ 32,  34],
       [ 36,  38],
       [ 40,  42],
       [ 44,  46],
       [ 48,  50],
       [ 52,  54],
       [ 56,  58],
       [ 60,  62],
       [ 64,  66],
       [ 68,  70],
       [ 72,  74],
       [ 76,  78],
       [ 80,  82],
       [ 84,  86],
       [ 88,  90],
       [ 92,  94],
       [ 96,  98],
       [100, 102],
       [104, 106],
       [108, 110],
       [112, 114],
       [116, 118],
       [120, 122],
       [124, 126],
       [128, 130],
       [132, 134],
       [136, 138],
       [140, 142],
       [144, 146],
       [148, 150],
       [152, 154],
       [156, 158],
       [160, 162],
       [164, 166],
       [168, 170],
       [172, 174],
       [176, 178],
       [180, 182],
       [184, 186],
       [188, 190],
       [192, 194],
       [196, 198],
       [200, 202],
       [204, 206],
       [208,

In [19]:
n=n.reshape(125,4)

In [20]:
n

array([[  0,   2,   4,   6],
       [  8,  10,  12,  14],
       [ 16,  18,  20,  22],
       [ 24,  26,  28,  30],
       [ 32,  34,  36,  38],
       [ 40,  42,  44,  46],
       [ 48,  50,  52,  54],
       [ 56,  58,  60,  62],
       [ 64,  66,  68,  70],
       [ 72,  74,  76,  78],
       [ 80,  82,  84,  86],
       [ 88,  90,  92,  94],
       [ 96,  98, 100, 102],
       [104, 106, 108, 110],
       [112, 114, 116, 118],
       [120, 122, 124, 126],
       [128, 130, 132, 134],
       [136, 138, 140, 142],
       [144, 146, 148, 150],
       [152, 154, 156, 158],
       [160, 162, 164, 166],
       [168, 170, 172, 174],
       [176, 178, 180, 182],
       [184, 186, 188, 190],
       [192, 194, 196, 198],
       [200, 202, 204, 206],
       [208, 210, 212, 214],
       [216, 218, 220, 222],
       [224, 226, 228, 230],
       [232, 234, 236, 238],
       [240, 242, 244, 246],
       [248, 250, 252, 254],
       [256, 258, 260, 262],
       [264, 266, 268, 270],
       [272, 2

In [24]:
# linspace is function which is similiar to arange 
o=np.linspace(0,10,100)
# we tell starting ,ending value, numberof intervals and splits up the intreval accordingly
o

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [25]:
o.resize(10,10)

In [33]:
o.resize(50,2)

In [31]:
o

array([[ 0.        ,  0.1010101 ],
       [ 0.2020202 ,  0.3030303 ],
       [ 0.4040404 ,  0.50505051],
       [ 0.60606061,  0.70707071],
       [ 0.80808081,  0.90909091],
       [ 1.01010101,  1.11111111],
       [ 1.21212121,  1.31313131],
       [ 1.41414141,  1.51515152],
       [ 1.61616162,  1.71717172],
       [ 1.81818182,  1.91919192],
       [ 2.02020202,  2.12121212],
       [ 2.22222222,  2.32323232],
       [ 2.42424242,  2.52525253],
       [ 2.62626263,  2.72727273],
       [ 2.82828283,  2.92929293],
       [ 3.03030303,  3.13131313],
       [ 3.23232323,  3.33333333],
       [ 3.43434343,  3.53535354],
       [ 3.63636364,  3.73737374],
       [ 3.83838384,  3.93939394],
       [ 4.04040404,  4.14141414],
       [ 4.24242424,  4.34343434],
       [ 4.44444444,  4.54545455],
       [ 4.64646465,  4.74747475],
       [ 4.84848485,  4.94949495],
       [ 5.05050505,  5.15151515],
       [ 5.25252525,  5.35353535],
       [ 5.45454545,  5.55555556],
       [ 5.65656566,

In [ ]:
# One major difference is reshape() does not change your data but resize() does change it. resize() first accommodates all the values in original array, after that if extra space is there (or size of new array is greater than original array), then it adds its own values

In [34]:
# several built in one functions and shortcuts in building arrays 

In [36]:
np.ones(10,10) # returns the arrays of ones

TypeError: data type not understood

In [37]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
# return array of zeros 
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [40]:
# creatign an diagonal array and all the diagonal values is going to be 1
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
y

array([2, 4, 5, 6])

In [42]:
#diaognal array
b=np.diag(y)
b

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [44]:
# creating an array with repeated values there are two ways

k=np.array([1,2,3,4,5]*5)
k


array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5])

In [46]:
k=np.array([[1,2,3,4,5]]*5)
k


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [48]:
p=np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [55]:
p.shape

(2, 3)

In [47]:
# using the build functions to create a repeated array
np.repeat([1,2,3,4],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [ ]:
#  now stacking elelments vertically 

In [50]:
a=np.vstack([p,p*2])
a

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [52]:
# stacking elements horizontally
b=np.hstack([p,p*2])
b

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [53]:
a.shape

(4, 4)

In [54]:
b.shape

(2, 6)

In [57]:
# operations

In [59]:
x=np.array([1,2,3])
y=np.array([4,5,6])
x+y

array([5, 7, 9])

In [61]:
k=x*y
k

array([ 4, 10, 18])

In [62]:
# raising all the values in an array to the power 
k**2

array([ 16, 100, 324], dtype=int32)

In [64]:
# dot product of two numbers
x.dot(y)

32

In [65]:
y

array([4, 5, 6])

In [66]:
z=np.array([y,y**2])

In [67]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [69]:
# doing transpose of an array
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [87]:
a=np.array([-4,-2,1,3,5])
a

array([-4, -2,  1,  3,  5])

In [88]:
a.sum()

3

In [89]:
a.mean()

0.6

In [90]:
a.max()

5

In [91]:
a.min()

-4

In [92]:
a.mean()

0.6

In [93]:
a.std()

3.2619012860600183

In [94]:
# to find index of maximum or minimum value 
a.argmax()

4

In [95]:
a.argmin()

0

In [ ]:
# indexing amd slicing 

In [96]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [97]:
s[0]

0

In [98]:
s[0:11]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [99]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [101]:
r=np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [103]:
# element at second row second column 
r[2,2]

14

In [104]:
r[3,3:6]

array([21, 22, 23])

In [107]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [109]:
# to get elements which is greater than 30
r[r>30]

array([31, 32, 33, 34, 35])

In [110]:
# in the give matrix we are trying to assign values which is greater than equal to 30 
r[r>30]=30

In [111]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [113]:
# now copying all the elements of one array to another array 
r_copy=r.copy()
r_copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [114]:
r_copy.sum()

615

In [115]:
# now trying to intialize all the values in array to sum value 
r_copy[:]=100
r_copy

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [117]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)
print(new)

[[0 0 1]
 [1 1 1]]
[[0 0 1]
 [1 1 1]]


In [118]:
# iterating over arrays 