In [1]:
# getting started with basics of numpy 


In [2]:
import numpy as np

In [3]:
mylist=[1,2,3,4,5]
#  converting list into an array

x=np.array(mylist)
x

array([1, 2, 3, 4, 5])

In [4]:
y=np.array([2,4,5,6,])
y

array([2, 4, 5, 6])

In [5]:
# making a multidimensional array


In [8]:
list1=[1,2,3]
list2=[3,4,5]
m=np.array([list1,list2])
m

array([[1, 2, 3],
       [3, 4, 5]])

In [10]:
#  two know the built in function of the array 
m.shape

(2, 3)