In [1]:
import numpy as np
import math


In [2]:
list1=[12,3,4,4,5,5,6]
a=np.array(list1)

In [3]:
a

array([12,  3,  4,  4,  5,  5,  6])

In [4]:
a.ndim# getiing dimensional array 

1

In [5]:
b=np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
b.shape

(2, 4)

In [8]:
c=np.array([12,2,34,4,5,6,7,8.10])
c

array([12. ,  2. , 34. ,  4. ,  5. ,  6. ,  7. ,  8.1])

In [9]:
d=np.zeros((4,5))

In [10]:
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
d=np.ones((4,4,))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# genderating random number 
d=np.random.rand(2,3)

In [13]:
d

array([[0.04773401, 0.3649063 , 0.85274767],
       [0.38696484, 0.5539603 , 0.07977407]])

In [14]:
f=np.arange(10,50,2) # here third number is diffrwence between two numbers 

In [15]:
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [16]:
k=np.linspace(0,2,40) # here third number indicated total no of numbers generated between first and second numbers 

In [17]:
k

array([0.        , 0.05128205, 0.1025641 , 0.15384615, 0.20512821,
       0.25641026, 0.30769231, 0.35897436, 0.41025641, 0.46153846,
       0.51282051, 0.56410256, 0.61538462, 0.66666667, 0.71794872,
       0.76923077, 0.82051282, 0.87179487, 0.92307692, 0.97435897,
       1.02564103, 1.07692308, 1.12820513, 1.17948718, 1.23076923,
       1.28205128, 1.33333333, 1.38461538, 1.43589744, 1.48717949,
       1.53846154, 1.58974359, 1.64102564, 1.69230769, 1.74358974,
       1.79487179, 1.84615385, 1.8974359 , 1.94871795, 2.        ])

In [18]:
# normal addition,subtraction,multiplication,diviison

In [19]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=a+b

In [20]:
c

array([ 7,  9, 11, 13, 15])

In [21]:
c=abs(a-b)
c

array([5, 5, 5, 5, 5])

In [22]:
d=a*b
d

array([ 6, 14, 24, 36, 50])

In [23]:
f=np.array([-0,-1,-2,-5,-10,0])


In [24]:
c=(f-32)*(5/9)
c


array([-17.77777778, -18.33333333, -18.88888889, -20.55555556,
       -23.33333333, -17.77777778])

In [25]:
# boolrean array if the condition is true it writtens false and true based on condition
c>20

array([False, False, False, False, False, False])

In [26]:
a=np.array([[12,1],[21,2],[32,33],[89,100],[100,1]])
b=np.array([[11,1],[21,2],[31,33],[89,100],[100,1]])
a*b

array([[  132,     1],
       [  441,     4],
       [  992,  1089],
       [ 7921, 10000],
       [10000,     1]])

In [27]:
# max,min,mean,sum,median values
print(a.max())

100


In [30]:
print(a[0].sum())

13


In [31]:
a=np.array([1,2,3,4,5])
a.sum()
a.min()
a.max()
a.mean()

3.0

In [32]:
print(a.sum())
print(a.min())


15
1
