In [1]:
import numpy as np
import math


In [6]:
list1=[12,3,4,4,5,5,6]
a=np.array(list1)

In [7]:
a

array([12,  3,  4,  4,  5,  5,  6])

In [10]:
a.ndim# getiing dimensional array 

1

In [12]:
b=np.array([[1,2,3,4],[5,6,7,8]])

In [14]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
b.shape

(2, 4)

In [18]:
c=np.array([12,2,34,4,5,6,7,8.10])
c

array([12. ,  2. , 34. ,  4. ,  5. ,  6. ,  7. ,  8.1])

In [19]:
d=np.zeros((4,5))

In [20]:
d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
d=np.ones((4,4,))
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
# genderating random number 
d=np.random.rand(2,3)

In [25]:
d

array([[0.25993438, 0.02100407, 0.66442198],
       [0.69180809, 0.16840063, 0.19547162]])